my:
  server:
    #ucloud 云
    addr: 106.75.107.221
    #华为云(deprecated)
    #addr: 114.116.199.250
spring:
  datasource:
    url: jdbc:mysql://${my.server.addr}:3306/mall_ams?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: tarena2017Up;
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:8848
  application:
    name: mall-ams
  jackson:
    # 总是显示
    default-property-inclusion: always
  redis:
    host: ${my.server.addr}
    port: 6379

dubbo:
  application:
    name: mall-ams
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    check: false
logging:
  level:
    cn.tedu.mall: trace