my:
  server:
    #本地虚拟机
    #addr: 192.168.137.150
    #ucloud 云
    addr: 106.75.107.221
    #华为云
    #addr: 114.116.199.250
# 日志显示级别
logging:
  level:
    cn.tedu.mall: trace
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      config:
        server-addr: ${my.server.addr}:8848
        group: DEFAULT_GROUP
        file-extension: yml
      discovery:
        server-addr: ${my.server.addr}:8848
    gateway:
      discovery:
        #动态路由,发现的服务都会自动添加到路由中
        locator:
          enabled: true
